Get http://localhost:4000/api/notes
Authorization: Bearer 51347acd-08af-4695-a360-cc3da6edafa4

###

POST http://localhost:4000/api/publish
Content-Type: application/json
Authorization: Bearer 14de1e17-492c-46a9-85eb-bdad3d04149f

{
    "username": "test",
    "title" : "from admin",
    "describe" : "do it four do it four do it four do it four do it four"
}

###

Get http://localhost:4000/api/delete/All

###
Get http://localhost:4000/api/642c7c4374ad74111d4a34ad

###
POST http://localhost:4000/api/register
Content-Type: application/json

{
    "username" : "test",
    "password" : "123456"
}
###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "username" : "test2",
    "password" : "123456"
}

###

Get http://localhost:4000/api/getUsers
Authorization: Bearer 96365323-be55-4be5-afd7-fa1815bdf72b

###
###

Get http://localhost:4000/api/hello
